Improved spelling and upgraded to Samply design / colour scheme
samply/manifest pull request #2
Opened 2019-08-14 11:41 UTC by dolchchr

Improvements done:
- English spelling improved (thanks to Cecilia et. al.)
- Official Samply Logo added
- Design and colour scheme adapted to the official Samply Logo

2019-08-14 11:49 UTC, alexanderkiel reviewed
Why did you add those transitions?

2019-08-14 11:52 UTC, alexanderkiel reviewed
Can you please use `<p>` for paragraphs and remove all `<br>`'s.

2019-08-14 11:52 UTC, dolchchr commented
> Why did you add those transitions?

for a smoother hover effect on weblinks

2019-08-14 11:53 UTC, alexanderkiel commented
> > Why did you add those transitions?
> 
> for a smoother hover effect on weblinks

No I mean the transitions on the title header.

2019-08-14 11:59 UTC, dolchchr commented
> > > Why did you add those transitions?
> > 
> > 
> > for a smoother hover effect on weblinks
> 
> No I mean the transitions on the title header.

I was not sure about bg-colour and with this effect it was easy to compare difference colours. Finally i choose black over white (over all others) but i liked the effect and didnt remove it. small easteregg.

2019-08-14 12:03 UTC, alexanderkiel commented
> > > > Why did you add those transitions?
> > > 
> > > 
> > > for a smoother hover effect on weblinks
> > 
> > 
> > No I mean the transitions on the title header.
> 
> I was not sure about bg-colour and with this effect it was easy to compare difference colours. Finally i choose black over white (over all others) but i liked the effect and didnt remove it. small easteregg.

Or simply a [Duck](https://blog.codinghorror.com/new-programming-jargon/). :-)

2019-08-14 12:09 UTC, dolchchr commented
> > > > > Why did you add those transitions?
> > > > 
> > > > 
> > > > for a smoother hover effect on weblinks
> > > 
> > > 
> > > No I mean the transitions on the title header.
> > 
> > 
> > I was not sure about bg-colour and with this effect it was easy to compare difference colours. Finally i choose black over white (over all others) but i liked the effect and didnt remove it. small easteregg.
> 
> Or simply a [Duck](https://blog.codinghorror.com/new-programming-jargon/). :-)

By the way: Do you also prefer black over white? I think its the best contrast to the green/gray logo, but looks a little bit "unusual". White fits good to the site, but contrast to the green is (too) low in my opinion.

2019-08-14 12:14 UTC, alexanderkiel commented
> > > > > > Why did you add those transitions?
> > > > > 
> > > > > 
> > > > > for a smoother hover effect on weblinks
> > > > 
> > > > 
> > > > No I mean the transitions on the title header.
> > > 
> > > 
> > > I was not sure about bg-colour and with this effect it was easy to compare difference colours. Finally i choose black over white (over all others) but i liked the effect and didnt remove it. small easteregg.
> > 
> > 
> > Or simply a [Duck](https://blog.codinghorror.com/new-programming-jargon/). :-)
> 
> By the way: Do you also prefer black over white? I think its the best contrast to the green/gray logo, but looks a little bit "unusual". White fits good to the site, but contrast to the green is (too) low in my opinion.

I wouldn't use boxes for headlines at all. But I think, we can improve in the styling in a next PR.

2019-08-15 08:41 UTC, johnlinde approved these changes

2019-08-15 08:43 UTC, TasDeniz approved these changes

2019-08-15 08:49 UTC, noemide approved these changes

2019-08-15 08:59 UTC, alexanderkiel requested changes

2019-08-15 08:59 UTC, alexanderkiel commented on index.html
> +<h1><img src="./Samply.png" alt="Samply"><b style="vertical-align:super"> manifest<b></h1>
Please close the `b` tag here.

2019-08-15 08:59 UTC, alexanderkiel commented on index.html
>  </html>
A newline at the end of file would be good.

2019-08-15 09:26 UTC, BjoernKrollGba approved these changes

2019-08-15 10:04 UTC, alexanderkiel approved these changes

2019-08-15 10:57 UTC, merged